name: Terraform validate staging

on:
  pull_request:
    paths: &terraform_paths
      - 'terraform/environments/staging/**/*.tf'
      - 'terraform/environments/staging/**/*.tfvars'
      - 'terraform/modules/**/*.tf'
      - '.github/workflows/terraform-validate-staging.yml'
    branches: &branches
      - main
      - develop

  push:
    paths: *terraform_paths
    branches: *branches
  
jobs:
  terraform-validate-staging:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_FOLDER: terraform
      TERRAFORM_WORKSPACE: terraform/environments/staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform fmt
        working-directory: ${{ env.TERRAFORM_FOLDER }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ env.TERRAFORM_WORKSPACE }}
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ${{ env.TERRAFORM_WORKSPACE }}
        run: terraform validate